### PR TITLE
CI

### PR DESCRIPTION
**Pull request by tsx**
Main site is deployed with github actions. However we don't have built previews on individual PRs. This is an attempt to provide them.

### CODE REVIEW

**Comment by tsx** [comment]
Unfortunately github actions don't allow [HTML previews](https://github.com/actions/upload-artifact/issues/3#issuecomment-598820814). The uploaded artifact can only be downloaded as a zip file.

Options are:
- use a separate CI provider to build and host html previews, like Circle
- have reviewers download a zip file
- don't provide previews at all

**Comment by philfreo** [comment]
@craigmdennis is taking a crack at a new site setup. Stay tuned.

**Comment by tsx** [comment]
@philfreo cool, feel free to close this PR if it's not aligned with other effort.

**Comment by philfreo** [comment]
If this is helpful already then go for it. Just a heads up things may change more soon.

**Comment by craigmdennis** [comment]
@tsx Is the aim to preview posts or changes to the site itself? If the former, I'm working on a solution using Netlify CMS (standalone) and their editorial workflow: https://www.netlifycms.org/docs/configuration-options/#publish-mode

They also offer 'preview links' which would aid in the latter but would require a service like Vercel or Netlify.

**Comment by tsx** [comment]
The intent is to have preview links on PRs for reviewers - mainly for post contents but in visual context of the site itself. For basic textual post content, previewing markdown in the Changes tab on the PR is good enough for me - but obviously it looks like github does - and the images are either not displayed or way off.

No production deploy changes intended at all. 

 didn't achieve what I wanted because GH doesn't support hosting html for previews, and I didn't want to involve Circle because there might be other options, included the ones you mentioned like Vercel.

**Comment by craigmdennis** [comment]
Closing in favour of #24 which resolves previewing with Vercel.

**Pull request closed without merging**
